name: macOS Application CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        # os: [macos-11.0, macos-12, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Build Swift Application
        run: |
          # xcode-select -p
          # ls `xcode-select -p`/Platforms/MacOSX.platform/Developer/SDKs
          pwd

        #swiftc -o hello main.swift

      # - name: Create DMG
      #   run: |
      #     mkdir -p MyApp.app/Contents/MacOS
      #     mv hello MyApp.app/Contents/MacOS/
      #     hdiutil create MyApp-${{ github.run_number }}.dmg -volname "MyApp" -srcfolder MyApp.app
      # - name: Upload DMG
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: MyApp-${{ github.run_number }}-${{ matrix.os }}.dmg
      #     path: MyApp-${{ github.run_number }}.dmg
